repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    # -   id: check-added-large-files
    -   id: check-ast
    -   id: detect-private-key
    -   id: check-yaml

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.3.0
    hooks:
    -   id: ruff
        args: [--fix]
        exclude: ^(runs|dev)/.*\.py$  # Skip Python files in these folders
    -   id: ruff-format
